### ISSUE TITLE
js error

### ISSUE THREAD

**Issue by mengmengisfull** [ThunbergOlle/SteamTradeBot#18]
hello,
i got something wrong
![image](https://user-images.githubusercontent.com/12983973/60768407-4619b680-a0f6-11e9-9535-846d16a0e016.png)
i can't find EPersonaState ,so i need your help,thank you very mach!

**Comment by mengmengisfull** [comment]
![image](https://user-images.githubusercontent.com/12983973/60768435-7d886300-a0f6-11e9-8ba1-5f45dcdba4c7.png)
this cmd picture,thanks

**Comment by ThunbergOlle** [comment]
Can you send the debug.log file?

**Comment by mengmengisfull** [comment]
[20:31:3] Loaded debug.
[20:31:3] New tradeoffer-manager was setup.
[20:31:3] Tried to logon with account credentials
[20:31:3] Loaded App
[20:31:4] Loaded BrowserMenu
[20:37:21] App Shutdown

![image](https://user-images.githubusercontent.com/12983973/60823976-5b1c4580-a1db-11e9-9f68-c89053192230.png)

thank you very much !

**Comment by ThunbergOlle** [comment]
I don't think you are using the correct login credentials.

**Comment by ThunbergOlle** [comment]
Hello. No it doesn't have to do with the login credentials. I found the issue and fixed it in this commit: https://github.com/ThunbergOlle/SteamTradeBot/commit/a235a1b643367352ffc35dd4574d3cdd10293fe6

You update the bot!

**Comment by mengmengisfull** [comment]
thank you very  very very very very much!!!!!!it works!
