### ISSUE TITLE
i move the dir to another conputer ,then it doesn't works

### ISSUE THREAD

**Issue by mengmengisfull** [ThunbergOlle/SteamTradeBot#20]
Hello,may you help me ?
i can run it in my computer ,but when i move the dir to another computer ,it looks something wrong like this
![image](https://user-images.githubusercontent.com/12983973/62638637-7318ed80-b970-11e9-9141-1c17336d9f8b.png)
then it doesn't change.
please help me ,very very thank you!

**Comment by mengmengisfull** [comment]
is looks like doesn't login ,because i change secret to a wrong secret

**Comment by mengmengisfull** [comment]
![image](https://user-images.githubusercontent.com/12983973/62639736-bffdc380-b972-11e9-901a-d9ac7b65dfa8.png)

**Comment by mengmengisfull** [comment]
![image](https://user-images.githubusercontent.com/12983973/62639793-defc5580-b972-11e9-8603-8a2616b23a7a.png)

this is my log,thank you very much !

**Comment by ThunbergOlle** [comment]
Hello.

Please check your login credentials so they are correct. As you can see, it can not log in.

Check identity secret, shared secret, password and username.

**Comment by mengmengisfull** [comment]
i checked my secerts,password and username,both right ones and wrong ones can't work.it looks like that nothing happens after the start.bat opened.

**Comment by ThunbergOlle** [comment]
Are you running the bot on a mac?

The bot doesn't support Mac.

**Comment by mengmengisfull** [comment]
no , i don't have a mac lol
i run it on winserver2008.
because i can't resolve this question,i try another way --i want to change a place to run the code,maybe on win10.
thack you very very much and i will still try to solve the problem.

**Comment by ThunbergOlle** [comment]
Yes. Try windows 10.
