### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kotik1998** [ThunbergOlle/SteamTradeBot#3]
Hi, what's wrong with it?
i inserted everything correctly
http://prntscr.com/krw6xh

**Comment by kotik1998** [comment]
also i have these node messages
http://prntscr.com/krw8mp

**Comment by kotik1998** [comment]
erm sorry to say but i entered the correct data on config.json all of it

**Comment by kotik1998** [comment]
ok nvm, i tried with other account-bot that i have and it worked.. 
well then the only thing im not sure is the http://prntscr.com/krw8mp

**Comment by ThunbergOlle** [comment]
The warning is showed because I forgot to set a callback when writing to config.json (./modules/config.js:10) 

It should be fixed if you update the bot! (Commit: https://github.com/ThunbergOlle/SteamTradeBot/commit/46e9c6db2efe70862aefbce6c45d277ae21ce8e6)

Let me know if it worked!
👍

**Comment by kotik1998** [comment]
the erros have dissapeared!
but is this normal on the bot http://prntscr.com/ksapao 
ive sent this offer http://prntscr.com/ksapii

**Comment by ThunbergOlle** [comment]
Yes I'm aware of that bug. I'm guessing that you sent the trade offers while the bot was offline. Then the logs can seem kind of messy sometimes. I will try to fix this as soon as possible, but yes it's unfortunately normal. Going to look in to this in later updates.

**Comment by kotik1998** [comment]
nope i did it live when bot was online

**Comment by ThunbergOlle** [comment]
Fixed lots of bugs and weird things that I did to the code in the past in this commit: https://github.com/ThunbergOlle/SteamTradeBot/commit/4d21d631ffbed47615921784721a43da26ef3092

It should be working but I'm still not sure how to fix that bug that you got. I can hopefully fix it tomorrow!

Of course I can add you on discord. I'm not sure if that username and tag you sent me is the right one. :/ Anyway if you want to add me instead: OlleThunberg#5944

**Comment by kotik1998** [comment]
just donwloaded the last comit, is this normal to happen?
http://prntscr.com/kt3hcl
i traded with the bot when he was on, no other trades were pending all live

**Comment by ThunbergOlle** [comment]
That's not normal no. I did add some small stuff and didn't try it out before I committed it. Fixing it in a few hours. 

But I don't think it affected that. I'm pretty sure. 

It's weird because I don't really get these errors on my machine. I may have to add some kind of debugging inside a file soon. Let me say about 1-2 days.

**Comment by ThunbergOlle** [comment]
Hello! 👋 
That took longer than expected. I've been up to some other projects over the week.
Anyways the issue that you are having is still weird but I would suggest that you update to the latest version. I added a debugger tool so I can have some understanding on what's going on!

Commit: https://github.com/ThunbergOlle/SteamTradeBot/commit/48b349c194e0ca399e2b0764daf9e0b2ee7b98be

Please send me the debug log! 👍

**Comment by ThunbergOlle** [comment]
Fixed the isssues in this commit: https://github.com/ThunbergOlle/SteamTradeBot/commit/a0d1d4ccbbebc5c44bfbc69b3d1cfb774818fc58
⭐️ 

I'm going to close the issue now. Thanks for reporting the bug! 👍
