### ISSUE TITLE
start.bat keeps giving this error, even thought it had ran before and worked fine.

### ISSUE THREAD

**Issue by HelloThere57** [ThunbergOlle/SteamTradeBot#34]
![image](https://user-images.githubusercontent.com/63324125/94937636-d54e7f00-049d-11eb-9cf1-007d20df7adc.png)
I ran it before and it worked, but the second time I tried to run it I got this error.

**Comment by ThunbergOlle** [comment]
Did you solve it?

Otherwise It's the config.json file that's throwing an error. Trying validating it.
