### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by vladikantimag** [ThunbergOlle/SteamTradeBot#4]
Hello. 
The thing is I got some error.
I have done all steps from README.
And when I try to run "start.bat" thins thing happens: 

https://prntscr.com/kxgmtc

I didn't change anything in "main.js"
Help me please :)

**Comment by ThunbergOlle** [comment]
Hello! 👋 

Inside main.js line 130 there was a wrong token, this should be fixed in commit: https://github.com/ThunbergOlle/SteamTradeBot/commit/3a09b13b372d60a8c72e3d1bbd6742f77f5f93a7

You will have to update the files in order for it to take effect.
Let me know if it worked or not! 😄

**Comment by vladikantimag** [comment]
It works thank you so much!

**Comment by vladikantimag** [comment]
I have one more question. 
Can I use it for RUST? And can I use it for few games at the same time?
Sorry for my English :D

**Comment by ThunbergOlle** [comment]
1. Yes you can use it for rust if you change the config file to match the appid of rust (252490) 👍 
2. No this current version does not support it 😢 I may add that in later versions.
