### ISSUE TITLE
Nothing happen when bot gets an offer

### ISSUE THREAD

**Issue by vladikantimag** [ThunbergOlle/SteamTradeBot#5]
Hi again.
I just tried to test the bot, bot got trade offer. Then nothing happened :(

**Comment by ThunbergOlle** [comment]
Hi, 👍 
May I have some more information on how it looks inside the console window?
Does the bot recieve the offer and doesn't handle it or what's happening? 
Did you send some items to the bot for free? If so: You will have to update to the latest version. (Commit: https://github.com/ThunbergOlle/SteamTradeBot/commit/48b349c194e0ca399e2b0764daf9e0b2ee7b98be)
Also in this commit: (https://github.com/ThunbergOlle/SteamTradeBot/commit/48b349c194e0ca399e2b0764daf9e0b2ee7b98be) I made a debugging tool. Would love if you would like to use it and send me the debug.log file so I can take a closer look at the problem. 👀 

As before, an update will be required. ⬇️

**Comment by vladikantimag** [comment]
I updated main.js with "48b349c" and got new error.

https://prnt.sc/kxnxe3

I think it will never work for me, I'm so unlucky :(

**Comment by ThunbergOlle** [comment]
Huh, that's very weird. It should work fine from my testing... 
https://prnt.sc/kxq634
Are you sure that you setup everything correct in the config.json folder? 📘 
Take a closer look at this line inside your config.json file:
https://prnt.sc/kxq6z5

Overall that's a very weird issue that should not appear. The error is pointing towards a character that's commented out. 
What version of Node.js are you using? To check: "Windows + R" then type "cmd" and press enter. Then you run the command "node -v"

Don't give up. We will make this work for you! ❤️

**Comment by vladikantimag** [comment]
Hello

**Comment by ThunbergOlle** [comment]
Alright, I'm going to close this issue right now because it seems to be inactive.
